### ISSUE TITLE
dispayErrors disables TYPO3-Backend in IEs

### ISSUE THREAD

**Issue by dominho** [agentur-markkom/Manual#6]
The following line in the AdditionalConfiguration disables the TYPO3-Backend in Internet-Explorers:

$GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = '1';

**Comment by dominho** [comment]
Add the following lines to the AdditionalConfiguration:

// Check if Browser is an IE
if (isset($_SERVER['HTTP_USER_AGENT']) && (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== false)){
        $GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = '0';
} else {
        $GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = '1';
}

**Comment by kathangeorg** [comment]
```
// Check if Browser is an IE
if (isset($_SERVER['HTTP_USER_AGENT']) 
    && (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== false)){
        $GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = '0';
} else {
        $GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = '1';
}
```

**Comment by kathangeorg** [comment]
fixed by @dominho
