### ISSUE TITLE
LazyLoading in IE

### ISSUE THREAD

**Issue by dominho** [agentur-markkom/Manual#7]

**Comment by dominho** [comment]
LazyLoading Script forces the following error:
unable to get value of the property 'add': object is null or undefined (line 20)

**Comment by kathangeorg** [comment]
fixed

/typo3conf/ext/t2page/Resources/Public/Assets/Libraries/echo/dist/use_echo.js

```
// fucking IE < 10 ;)
- element.classList.add('fadeIn');
+ element.className += ' fadeIn';
```
